name: GoogleArtifactRegistry

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: build and push the docker images
        env:
          GOOGLE_PROJECT: ${{ secrets.GCLOUD_PROJECT_ID }}
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev
          docker build -t europe-west4-docker.pkg.dev/$GOOGLE_PROJECT/demo/auth:latest --build-arg KEYFILE_CONTENT="${{ secrets.KEYFILE_CONTENT }}" --build-arg ACCESS_TOKEN_PUBLIC_KEY="${{ secrets.ACCESS_TOKEN_PUBLIC_KEY }}" --build-arg ACCESS_TOKEN_PRIVATE_KEY="${{ secrets.ACCESS_TOKEN_PRIVATE_KEY }}" --build-arg REFRESH_PRIVATE_KEY="${{ secrets.REFRESH_PRIVATE_KEY }}" --build-arg REFRESH_PUBLIC_KEY="${{ secrets.REFRESH_PUBLIC_KEY }}" --build-arg MONGODB_CONNECTION_STRING_AUTH="${{ secrets.MONGODB_CONNECTION_STRING_AUTH }}" --build-arg GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" --build-arg GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" ./WOA/auth-microservice
          docker push europe-west4-docker.pkg.dev/$GOOGLE_PROJECT/demo/auth:latest
          docker build -t europe-west4-docker.pkg.dev/$GOOGLE_PROJECT/demo/notifications:latest --build-arg SMTP_AUTH_USER="${{ secrets.SMTP_AUTH_USER }}" --build-arg SMTP_AUTH_PASS="${{ secrets.SMTP_AUTH_PASS }}" ./WOA/notifications-microservice
          docker push europe-west4-docker.pkg.dev/$GOOGLE_PROJECT/demo/notifications:latest
          docker build -t europe-west4-docker.pkg.dev/$GOOGLE_PROJECT/demo/postfeed:latest --build-arg KEYFILE_CONTENT="${{ secrets.KEYFILE_CONTENT }}" --build-arg MONGODB_CONNECTION_STRING_POSTFEED="${{ secrets.MONGODB_CONNECTION_STRING_POSTFEED }}" --build-arg ACCESS_TOKEN_PUBLIC_KEY="${{ secrets.ACCESS_TOKEN_PUBLIC_KEY }}" --build-arg REFRESH_PUBLIC_KEY="${{ secrets.REFRESH_PUBLIC_KEY }}" ./WOA/postfeed-microservice
          docker push europe-west4-docker.pkg.dev/$GOOGLE_PROJECT/demo/postfeed:latest
          docker build -t europe-west4-docker.pkg.dev/$GOOGLE_PROJECT/demo/client:latest ./WOA/client
          docker push europe-west4-docker.pkg.dev/$GOOGLE_PROJECT/demo/client:latest

      - name: deploy to gke
        env:
          GOOGLE_PROJECT: ${{ secrets.GCLOUD_PROJECT_ID }}
        run: |
          gcloud container clusters get-credentials woa-dev --region europe-west4-a
          sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" ./WOA/infrastructure/k8s/auth-clusterip-depl.yaml
          sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" ./WOA/infrastructure/k8s/client-clusterip-depl.yaml
          sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" ./WOA/infrastructure/k8s/notifications-clusterip-depl.yaml
          sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" ./WOA/infrastructure/k8s/postfeed-clusterip-depl.yaml
          kubectl apply --force -f ./WOA/infrastructure/k8s/auth-clusterip-depl.yaml
          kubectl apply --force -f ./WOA/infrastructure/k8s/client-clusterip-depl.yaml
          kubectl apply --force -f ./WOA/infrastructure/k8s/notifications-clusterip-depl.yaml
          kubectl apply --force -f ./WOA/infrastructure/k8s/postfeed-clusterip-depl.yaml
          kubectl apply --force -f ./WOA/infrastructure/k8s/rabbitmq-clusterip-depl.yaml
          kubectl apply --force -f ./WOA/infrastructure/k8s/rabbitmq-srv.yaml
          kubectl apply --force -f ./WOA/infrastructure/k8s/ingress-srv.yaml
          kubectl rollout restart deployment auth-depl
          kubectl rollout restart deployment client-depl
          kubectl rollout restart deployment notifications-depl
          kubectl rollout restart deployment postfeed-depl

  buffer:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Wait 10 min for the cluster to stabilize
        run: sleep 600

  zap_scan:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: buffer
    name: OWASP ZAP scan
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://woaapp.com'
          rules_file_name: '.zap/rules.tsv'
          fail_action: false
          cmd_options: '-a'
