name: GoogleArtifactRegistry

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2
      
    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
        
    - name: build and push the docker images
      env:
        GOOGLE_PROJECT: ${{ secrets.GCLOUD_PROJECT_ID }}
      run: |
        gcloud auth configure-docker europe-west4-docker.pkg.dev
        docker build -t europe-west4-docker.pkg.dev/$GOOGLE_PROJECT/demo/auth:latest ./WOA/auth-microservice
        docker push europe-west4-docker.pkg.dev/$GOOGLE_PROJECT/demo/auth:latest
     
