name: dockerize

on:
  push:
    branches:
      - 'dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context:
          - 'auth-microservice'
          - 'client'
          - 'postfeed-microservice'
          - 'notifications-microservice'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./WOA/${{ matrix.context }}
          push: true
          tags: tsankonedelchev/${{ matrix.context }}:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}
        env:
          ACCESS_TOKEN_PUBLIC_KEY: ${{ secrets.ACCESS_TOKEN_PUBLIC_KEY }}
          ACCESS_TOKEN_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN_PRIVATE_KEY }}
          REFRESH_PRIVATE_KEY: ${{ secrets.REFRESH_PRIVATE_KEY }}
          REFRESH_PUBLIC_KEY: ${{ secrets.REFRESH_PUBLIC_KEY }}
          MONGODB_CONNECTION_STRING_AUTH: ${{ secrets.MONGODB_CONNECTION_STRING_AUTH }}
          MONGODB_CONNECTION_STRING_POSTFEED: ${{ secrets.MONGODB_CONNECTION_STRING_POSTFEED }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          SMTP_AUTH_USER: ${{ secrets.SMTP_AUTH_USER }}
          SMTP_AUTH_PASS: ${{ secrets.SMTP_AUTH_PASS }}
        timeout-minutes: 20
