# name: Build and Deploy to GKE

# on:
#   push:
#     branches: [ "main" ]

# env:
#   PROJECT_ID: woa-dev-389512
#   GAR_LOCATION: europe-west4 # TODO: update region of the Artifact Registry
#   GKE_CLUSTER: woa-dev    # TODO: update to cluster name
#   GKE_ZONE: europe-west4-a   # TODO: update to cluster zone
#   DEPLOYMENT_NAME: gke-test # TODO: update to deployment name
#   REPOSITORY: samples # TODO: update to Artifact Registry docker repository
#   IMAGE: static-site

# jobs:
#   deployment:
#     runs-on: windows-latest
#     # Add "id-token" with the intended permissions.
#     permissions:
#       contents: 'read'
#       id-token: 'write'

#     steps:
#     - id: 'auth'
#       uses: 'google-github-actions/auth@v1'
#       with:
#         workload_identity_provider: 'projects/122782001930/locations/global/workloadIdentityPools/github-actions/attribute.repository/canko97/woa-app'
#         service_account: 'github-actions@woa-dev-389512.iam.gserviceaccount.com'

#     - name: 'Set up Cloud SDK'
#       uses: 'google-github-actions/setup-gcloud@v1'
#       with:
#         version: '>= 363.0.0'

#     - name: 'Use gcloud CLI'
#       run: 'gcloud components install skaffold'
