name: SonarQube with unit test coverage metrics
on:
  push:
    branches:
      - dev
jobs:
  sonarqube:
    name: sonarqube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          cd ./WOA/auth-microservice && npm install
          cd ../../
          cd ./WOA/postfeed-microservice && npm install
          cd ../../
      - name: Test and coverage
        run: |
          cd ./WOA/auth-microservice && npm run test
          cd ../../
          cd ./WOA/postfeed-microservice && npm run test
          cd ../../
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          ACCESS_TOKEN_PUBLIC_KEY: ${{ secrets.ACCESS_TOKEN_PUBLIC_KEY }}
          ACCESS_TOKEN_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN_PRIVATE_KEY }}
          REFRESH_PRIVATE_KEY: ${{ secrets.REFRESH_PRIVATE_KEY }}
          REFRESH_PUBLIC_KEY: ${{ secrets.REFRESH_PUBLIC_KEY }}
          MONGODB_CONNECTION_STRING_AUTH: ${{ secrets.MONGODB_CONNECTION_STRING_AUTH }}
          MONGODB_CONNECTION_STRING_POSTFEED: ${{ secrets.MONGODB_CONNECTION_STRING_POSTFEED }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          SMTP_AUTH_USER: ${{ secrets.SMTP_AUTH_USER }}
          SMTP_AUTH_PASS: ${{ secrets.SMTP_AUTH_PASS }}
